### ISSUE TITLE
AppRestrictSchema Default Value from XML not working.

### ISSUE THREAD

**Issue by SyedWasiHaider** [xamarin/monodroid-samples#102]
I just tried running the https://github.com/xamarin/monodroid-samples/tree/master/android5.0/AppRestrictionSchema and I changed the default value of the "can_say_hello" to true in the app_restrictions.xml file but nothing changed.  In fact, when I put a breakpoint to check the value of the restrictions bundle, it was empty.

I think the xml file is not being parsed/read correctly (if at all).

I ran this sample on a Nexus 7 (5.0.2)

![snip20151117_44](https://cloud.githubusercontent.com/assets/3202990/11228228/0b8c138c-8d40-11e5-9602-8489dba6bb36.png)

**Comment by pjcollins** [comment]
Fixed in master, the sample still requires further updating though due to changes in the upstream sample.
