### ISSUE TITLE
Buffer is closed exception

### ISSUE THREAD

**Issue by acaliaro** [xamarin/monodroid-samples#104]
https://www.dropbox.com/s/rysmys1osilumsn/Screenshot%202016-01-07%2015.28.06.png?dl=0

executing the phone app, I have this problem at startup

**Comment by Abhishekk360** [comment]
Thanks for Reporting this issue. I am unable to open the screencast provided above. That why issue is not clear to me. Could you please rechecked this issue with latest updated Sample or If possible to provide me more info regarding this issue.

Thanks!
