### ISSUE TITLE
Exception when app goes in OnStop()

### ISSUE THREAD

**Issue by acaliaro** [xamarin/monodroid-samples#105]
https://www.dropbox.com/s/dbu5nzalcavtkrw/Screenshot%202016-01-07%2018.46.45.png?dl=0

https://www.dropbox.com/s/ate7312bekgt92b/Screenshot%202016-01-07%2018.47.10.png?dl=0

[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: DataLayer.DataLayer, PID: 23702
[AndroidRuntime] java.lang.RuntimeException: Unable to stop activity {DataLayer.DataLayer/md5d53a7e868d2b29f1dd258e41ad0b3db9.MainActivity}: android.util.SuperNotCalledException: Activity {DataLayer.DataLayer/md5d53a7e868d2b29f1dd258e41ad0b3db9.MainActivity} did not call through to super.onStop()
[AndroidRuntime] 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3355)
[AndroidRuntime] 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3401)
[AndroidRuntime] 	at android.app.ActivityThread.access$1100(ActivityThread.java:139)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1320)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:102)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:149)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:5257)
[AndroidRuntime] 	at java.lang.reflect.Method.invokeNative(Native Method)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Method.java:515)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
[AndroidRuntime] 	at dalvik.system.NativeStart.main(Native Method)
[AndroidRuntime] Caused by: android.util.SuperNotCalledException: Activity {DataLayer.DataLayer/md5d53a7e868d2b29f1dd258e41ad0b3db9.MainActivity} did not call through to super.onStop()
[AndroidRuntime] 	at android.app.Activity.performStop(Activity.java:5558)
[AndroidRuntime] 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3352)
[AndroidRuntime] 	... 11 more

**Comment by olegoid** [comment]
Hello @acaliaro, we can't reproduce this bug. Could you provide additional details(reproductions case & your environment information)?

**Comment by acaliaro** [comment]
@olegoid sorry, it's very old and I don't remember the sample I have tried. Close it...
