### ISSUE TITLE
I Can't see service when run command line list service running on system

### ISSUE THREAD

**Issue by TheKop** [xamarin/monodroid-samples#111]
HI Xamarin Team
I already run your example
Start service
It say ok.
But when i check list service running on system . I can't found "DemoService"
Step by step as following :
adb shell
su
service list
===> my device print all service running on system
but i can't found "DemoService"

Could you tell me what is that mean?
I think your service type is difference with system service . So "service list" will not found
Do you have any suggest to fix this problem?

Why i do this? Because i want use "service" command line to call a your service and passing parameter to it like this example :
service call phone 2 s16 "+15084157509"

Please confirm
Thank you

**Comment by Abhishekk360** [comment]
Thanks for reporting this issue. I have filed the bug for the same. https://bugzilla.xamarin.com/show_bug.cgi?id=42207

Hence closing this issue.
Thanks!

**Comment by olegoid** [comment]
Please continue any discussions on this in Bugzilla.
