### ISSUE TITLE
BasicLocationSample - The "CreateAdditionalLibraryResourceCache" task failed unexpectedly

### ISSUE THREAD

**Issue by smillertime** [xamarin/monodroid-samples#112]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2,2): Error MSB4018: The "CreateAdditionalLibraryResourceCache" task failed unexpectedly.
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at Xamarin.Android.Tools.Files.CopyIfChanged(String source, String destination)
   at Xamarin.Android.Tasks.CreateAdditionalLibraryResourceCache.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() (MSB4018) (BasicLocationSample)

**Comment by VyshuRaj** [comment]
How to solve this problem?Everytime we are getting this.

**Comment by LucioMSP** [comment]
Try moving your project to a directory that has a shorter path (e.g. c:\X\project). 
I believe some of the file names being generated in later versions of Xamarin.Forms are now longer.

**Comment by VyshuRaj** [comment]
thank you so much sir

**Comment by NikolaiTsepalov** [comment]
It should not be closed.
You guys basically provided a workaround.
After getting "task failed unexpectedly" we have to Google it:(
The real fix would be to let the user know that project locates in the "deep" folder and solution cannot be compiled because of the path limit.
Looks like very long paths becoming a common problem. I saw similar problems

Thanks

**Comment by CRivasGomez** [comment]
> Try moving your project to a directory that has a shorter path (e.g. c:\X\project).
I believe some of the file names being generated in later versions of Xamarin.Forms are now longer

Thanks @LucioMSP 
That totally worked for me!
