### ISSUE TITLE
Java.Lang.NoClassDefFoundError: com.facebook.android.R$drawable

### ISSUE THREAD

**Issue by leeoades** [xamarin/monodroid-samples#12]
If you reference Mono.Facebook from a Mono for Android Application that doesn't have the package name com.facebook.android, then you get the following error:

Unhandled Exception:

Java.Lang.NoClassDefFoundError: com.facebook.android.R$drawable

Please help.

Thanks,
Lee.

**Comment by alirong** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已经收到您的邮件。谢谢
