### ISSUE TITLE
Location - Geofencing - Geofencing service is not available now Error

### ISSUE THREAD

**Issue by palakhirpara** [xamarin/monodroid-samples#131]
When I run it on actual device, it is giving me this error: [creating-and-monitoring-geofences] Geofence service is not available now. Status.IsSuccess from this line of code in MainActivity.cs results into false (instead of true) and thus printing the error message. 

var status = await LocationServices.GeofencingApi.RemoveGeofencesAsync(mGoogleApiClient,
					GetGeofencePendingIntent());   

It works sometime on the emulator. Does anyone how to get solve this issue?
Thanks in advance.

**Comment by Abhishekk360** [comment]
Thanks for reporting the issue. I am no longer to reproduce this issue at my end. I have checked this issue with latest updated sample. I have added the latitude and longitude of my current location. If I run the application on device. If I click on Remove Geofences then status.IsSuccess =true. Here is the screencast for the same: http://www.screencast.com/t/RVcaYHwNQ1sg

So as of now I am closing this issue. Please let me know if am missing something.

Thanks!
