### ISSUE TITLE
Android Fit Sensors Api Sample Isn't Working

### ISSUE THREAD

**Issue by mayur-tendulkar** [xamarin/monodroid-samples#139]
The sample mentioned here https://developer.xamarin.com/samples/monodroid/google-services%5CFitness%5CBasicSensorsApi/ doesn't work anymore. I think, it needs to be updated.

**Comment by gonzalonm** [comment]
Looks like Google didn't update this sample over 2 years: https://github.com/googlesamples/android-fit/tree/master/BasicSensorsApi
