### ISSUE TITLE
Resource.Drawable error

### ISSUE THREAD

**Issue by Eruoghene** [xamarin/monodroid-samples#151]
hi, i implemented same code as yours in this section

`static Posts[] mPosts = {
            new Posts() { mId = "0", mCaption = "Positivitea", mShortname = "positivitea", mAuthor = "Gabriel Esu", mSummary = "lorem 25", mImg = Resource.Drawable.5Img },
            new Posts() { mId = "1", mCaption = "Learn to Relax", mShortname = "learn_relax", mAuthor = "Etsy",  mSummary = "lorem 26", mImg = Resource.Drawable.2Img },
        };`

i'm getting an error in the Resource.Drawable  as "Resource.Drawable is a type which is not valid in this context"

**Comment by conceptdev** [comment]
Does your application have `Android` in its namespace? This is generally not recommended.

Try replacing the 
`mImg = Resource.Drawable.5Img` 
with
`mImg = global::Android.Resource.Drawable.5Img`

**Comment by Eruoghene** [comment]
It's working now, thanks
