### ISSUE TITLE
File not saved

### ISSUE THREAD

**Issue by gkowieski** [xamarin/monodroid-samples#156]
Just FYI, I don't think you are wired in for saving the file anymore.

**Comment by gkowieski** [comment]
um... I'm new to git so, I don't know if I posted that to the Camera2 project or not.

**Comment by cmenge** [comment]
I'm facing the same problem with the recently modified Camera2Basic application. `mCaptureSession.Capture(mPreviewRequestBuilder.Build(), mCaptureCallback,
                        mBackgroundHandler);` is the last breakpoint that is being triggered, then the app simply continues to show the preview. I can hit the picture button about 10 times after which the app crashes with a `NullReferenceException`. Given that it already takes thousands of lines of code just to take a picture, this isn't very reassuring. Not sure whether Xamarin or Android is to blame, but this seems overly complicated and fragile.

**Comment by BrightwellConsulting** [comment]
Hi There, I too am facing the same problem. It works just how I want it until it comes to saving the FIle. The "ImageAvailableListener" is never fired, and therefore the file is never saved. Just can't work out why???
Any help?

**Comment by caiogit** [comment]
facing the same problem. "ImageAvailableListener" is never fired,

**Comment by gkowieski** [comment]
@BrightwellConsulting, @caiogit :  Christoph,(@cmenge), suggested a nice fix for the issue.  The problem is the event is never wired in and they used the Owner property without testing for null.  Some minor changes got it back in the grove for me.  Hit me up if you need assistance with it.  I'm hoping they will publish an official fix so not so many people are bewildered by the solution as it sits now on git.

**Comment by cmenge** [comment]
@gkowieski thanks for the reminder. The fix is now checked in to my fork. I tested it on two devices successfully. Still doesn't work with the emulator, but that has always been a problem. 
Also, I only tested it with SdkVersion 23, which is not what is currently configured in the project file (24, i.e. Android 7.0)...

**Comment by owlstack** [comment]
Is this fixed yet? It's still not working for me? The image file is not saved. Can you show a way to save the file as a bitmap, so I can compress the image to save?

**Comment by owlstack** [comment]
@cmenge, I used your fork to get it to work. Thanks a bunch! Btw, I noticed that the camera2basic sample app takes lower resolution photos than native camera resolution photos. Any particular reason for that? Thanks!
