### ISSUE TITLE
Method for getting user info deprecated 

### ISSUE THREAD

**Issue by oozebra** [xamarin/monodroid-samples#161]
'IPeople.GetCurrentPerson(GoogleApiClient)' is obsolete: 'deprecated'	SigninQuickstart	

Along with many others.
Please Update!!!

**Comment by gonzalonm** [comment]
Related sample: https://github.com/xamarin/monodroid-samples/tree/fb9d4ed266bdf68bb1f9fa9933130b285712ec82/google-services/SigninQuickstart

**Comment by gonzalonm** [comment]
https://github.com/xamarin/monodroid-samples/issues/187
