### ISSUE TITLE
ITabListener and SearchView in ActionBarSherlock project

### ISSUE THREAD

**Issue by jayjan1234** [xamarin/monodroid-samples#164]
Hi All,
xamarin complains that it is unable to find refernece of searchView in Xamarin.ActionbarSherlockBinding.Widget.SearchView and Xamarin.ActionbarSherlockBinding.App.ActionBar.ITabListener . 

attached is the configuration of my project. can someone please help? thanks.

![image](https://cloud.githubusercontent.com/assets/10785467/20966037/97d64bc0-bccc-11e6-95b6-640fa197db92.png)

**Comment by gonzalonm** [comment]
Related sample: https://github.com/xamarin/monodroid-samples/tree/master/ActionBarSherlock

**Comment by gonzalonm** [comment]
Are you still having this problem?
