### ISSUE TITLE
Cannot combine custom titles with other title features

### ISSUE THREAD

**Issue by ReallyRad** [xamarin/monodroid-samples#166]
Hello,
when trying to run the example on a Sony Xperia Z compact, running API 21, I get a runtime error "You cannot combine custom titles with other title features". By looking up the error, I found that it is caused by using `RequestWindowFeature` and `Window.SetFeatureInt` at the same time. 

What is a way to circumvent this error?

**Comment by jmsargent9** [comment]
I'm having the same issue and it is very frustrating. Anyone know how to fix this?

**Comment by shamseen** [comment]
I am also having this issue! [This link](http://zacg.github.io/blog/2014/02/28/android-using-custom-header-title/) has helped get past the exception. Basically it has something to do with the theme being dumb

in AndroidManifest.xml : 
```xml
<manifest>
<application android:theme="@style/CustomTheme"></application>
</manifest>
```

add a styles.xml under /resources/values/ and then
``` xml
<?xml version="1.0" encoding="UTF-8" ?>
<resources>
    <style name="CustomTheme" parent="android:Theme.Holo">
        <item name="android:windowActionBar">false</item>
    </style>
</resources>
```
