### ISSUE TITLE
NoSuchMethodError when apk created in release mode for fused location services.

### ISSUE THREAD

**Issue by sasi210891** [xamarin/monodroid-samples#170]
When I try to generate release mode APK for fused location provider example, I'm getting following error. Kindly provide a fix for the issue.

java.lang.NoSuchMethodError: no non-static method "Lcom/google/android/gms/location/internal/zzd;.getLastLocation(Lcom/google/android/gms/common/api/GoogleApiClient;)Landroid/location/Location;"

**Comment by EagleTsui** [comment]
Same issue when create APK... feel Xamarin is not stable....back to java now
