### ISSUE TITLE
The type initializer for 'BluetoothLeGatt.BluetoothLeService' threw an exception.

### ISSUE THREAD

**Issue by braniomaster** [xamarin/monodroid-samples#178]
When I start the application, near Bluetooth LE devices are shown in the list. When I click on item I get the Unhandled exception: System.TypeInitializationException: The type initializer for 'BluetoothLeGatt.BluetoothLeService' threw an exception.

Please help.

**Comment by gonzalonm** [comment]
Related sample: https://github.com/xamarin/monodroid-samples/tree/master/BluetoothLeGatt

**Comment by gonzalonm** [comment]
https://github.com/xamarin/monodroid-samples/pull/89

**Comment by sebvinnac** [comment]
Someone has find a solution for this problem ?
