### ISSUE TITLE
How to configure Google Sign-In Sample

### ISSUE THREAD

**Issue by georgethms10** [xamarin/monodroid-samples#187]
I downloaded the application and tried to run it but it failed. In troubleshooting it is said **" Make sure you've authorized the app in the Google Developers Console before use"**  How to Do this. 
I have the client.json file from the console how to configure it in xamarin in visual studio

**Comment by gonzalonm** [comment]
Related sample: https://github.com/xamarin/monodroid-samples/tree/fb9d4ed266bdf68bb1f9fa9933130b285712ec82/google-services/SigninQuickstart

**Comment by gonzalonm** [comment]
We're updated this sample and added more instructions to setup this. You can find them here:

https://github.com/gonzalonm/monodroid-samples/tree/update_sign_in_sample/google-services/SigninQuickstart

However, we need to merge a support library update before this one. So, in the meantime, you can try to use this sample from the provided repo (this will be merged into master soon)

**Comment by pjcollins** [comment]
Should be resolved now that PR #222 is merged.
