### ISSUE TITLE
Not sure which file the layer-list goes into from section "Creating a Drawable for the Splash Screen"

### ISSUE THREAD

**Issue by gregdegruy** [xamarin/monodroid-samples#192]
From these docs https://developer.xamarin.com/guides/android/user_interface/creating_a_splash_screen/

**Comment by GeekJosh** [comment]
You create a drawable resource and that XML defines it. The file in the SplashScreen example for this repo is here: https://github.com/xamarin/monodroid-samples/blob/master/SplashScreen/SplashActivity/Resources/drawable/splash_screen.xml

**Comment by mgmclemore** [comment]
Updated the doc to explain where the file goes.
