### ISSUE TITLE
Camera2Raw fails on Google Pixel: "failed to configure camera"

### ISSUE THREAD

**Issue by tele-bird** [xamarin/monodroid-samples#194]
When I deploy this project to my Google Pixel device, it fails before opening camera preview with error: "failed to configure camera".

project: monodroid-samples/tree/master/android5.0/Camera2Raw

I was able to get it working by commenting out all code related to JpegImageReader.

**Comment by ahmad2smile** [comment]
Camera2Raw example is disgustingly bad code. Looks to me written by some automated system. Code examples like this make developers quite programming.

**Comment by kkarakk** [comment]
yup doesn't work on nexus6P either, this sample looks like it's been abandoned

**Comment by eliasdiegoperez** [comment]
Did you also have trouble taking the picture? The error message says to check the source code but I cannot find where I'm supposed to edit the source code to allow the picture to be taken

**Comment by eliasdiegoperez** [comment]
> When I deploy this project to my Google Pixel device, it fails before opening camera preview with error: "failed to configure camera".
> 
> project: monodroid-samples/tree/master/android5.0/Camera2Raw
> 
> I was able to get it working by commenting out all code related to JpegImageReader.

Do you know anyway to configure the camera for saving pictures in JPEG?

**Comment by kkarakk** [comment]
@eliasdiegoperez just use `https://github.com/jamesmontemagno/MediaPlugin` this library instead. very easy to use and works fine on xamarin.android

**Comment by eliasdiegoperez** [comment]
In the SetUpCameraOutputs() function I was able to diagnose where the error was coming from for the JpegImageReader. 
in this segment of the function:
if (mJpegImageReader == null || mJpegImageReader.getAndRetain() == null) {
                        mJpegImageReader = new RefCountedAutoCloseable<>(
                                ImageReader.newInstance(largestJpeg.getWidth(),
                                        largestJpeg.getHeight(), ImageFormat.JPEG, /*maxImages*/5));
                    }
If you change the largestJpeg.getWidth() and LargestJpeg.getHeight() to another pixel size it should work. I believe these numbers affect the resolution of the picture produced. 

This is what I changed mine to:
if (mJpegImageReader == null || mJpegImageReader.GetAndRetain() == null)
                        {
                            mJpegImageReader = new RefCountedAutoCloseable<ImageReader>(
                                ImageReader.NewInstance(720,
                                    1024, ImageFormatType.Jpeg, /*maxImages*/5));
                        }

Hope this can help someone in the future.
