### ISSUE TITLE
Foreground Service Demo: when click [Start Service] the Activity not refresh

### ISSUE THREAD

**Issue by yuzd** [xamarin/monodroid-samples#197]
when click [Start Service] 
then this code
```
startServiceButton.Enabled = false;
stopServiceButton.Enabled = true;
```
was be excuted!

but the activity still 
```
startServiceButton.Enabled = true;
stopServiceButton.Enabled = false;
```

the activity was refresh when i click the title of app.
why?

**Comment by gonzalonm** [comment]
I'm not sure what are you referencing. The samples shows how a service is executed in foreground (you can see a notification en notification area). When you start a service, "START SERVICE" button turns disabled and "STOP SERVICE" button turns enabled. I'm not seeing a wrong behavior here.

If you still seeing a wrong behavior, please provide us more information (a screenrecord would be great)

Thanks
