### ISSUE TITLE
Unhandled Exception:  Android.Util.AndroidRuntimeException: You cannot combine custom titles with other title features

### ISSUE THREAD

**Issue by gunnicus** [xamarin/monodroid-samples#198]
Hi, I'm trying to run this in Android 6.0, I got this error Unhandled Exception:  Android.Util.AndroidRuntimeException: You cannot combine custom titles with other title features on BluetoothChat.cs line 84 		SetContentView (Resource.Layout.main);

Please help.

**Comment by melsy6666** [comment]
https://stackoverflow.com/questions/12280303/feature-custom-title-cannot-combine-custom-titles-on-api-11-and-above   this fixed that for me

**Comment by gonzalonm** [comment]
Related sample: https://github.com/xamarin/monodroid-samples/tree/master/BluetoothChat

**Comment by gonzalonm** [comment]
I could not reproduce this issue in Android 6.0 device. Are you still having this problem?

**Comment by gunnicus** [comment]
Yes I'm using a Sumsung galaxy s5 with Android 6.0

**Comment by gonzalonm** [comment]
Did you try the proposed solution by @melsy6666 ?

**Comment by gunnicus** [comment]
Yes I did, the project built, but it is not functioning correctly, the menu is now showing.

**Comment by gonzalonm** [comment]
Please, could you paste here a screenshot of your screen? I could run this sample without that fix and it was fine.

**Comment by gunnicus** [comment]
Ok, this is the screen after I run this app, it doesn't give me device list.

![image](https://user-images.githubusercontent.com/4023477/31590180-b6888412-b257-11e7-86d5-35610e49360a.png)

**Comment by gonzalonm** [comment]
Ok, I've created a [new issue](https://github.com/xamarin/monodroid-samples/issues/226) to update this sample and see if that solves the problem
