### ISSUE TITLE
update services for new Android 8.0

### ISSUE THREAD

**Issue by joeblew99** [xamarin/monodroid-samples#210]
With android 8.0 Services has changed a fair bit.

Should the sample be updated ?
https://github.com/xamarin/monodroid-samples/tree/master/ApplicationFundamentals/ServiceSamples

**Comment by gonzalonm** [comment]
We're working on new updates for several samples. We'll update it soon. In the meantime, you can check this sample in this branch https://github.com/xamarin/monodroid-samples/tree/support-26.1.0/ApplicationFundamentals/ServiceSamples

Thanks

**Comment by joeblew99** [comment]
i have a few questions. 
The main one is how to install a Foreground app and Background Service iin the one APK 

Shoudl i ask here or there ?

**Comment by gonzalonm** [comment]
yeah, it is ok. I'll review it shortly

**Comment by gonzalonm** [comment]
answered here: https://github.com/xamarin/monodroid-samples/issues/211
We can close this issue and follow this thread in that issue
