### ISSUE TITLE
Xamarin.android Default FirebaseApp is not initialized in this process

### ISSUE THREAD

**Issue by Phoenix-GH** [xamarin/monodroid-samples#215]
I tried to run this example with my google-services.json and I'm facing the issue.

Xamarin.android Default FirebaseApp is not initialized in this process

Can you please try to resolve the issue?

**Comment by gonzalonm** [comment]
Are you referencing to this sample? https://github.com/xamarin/monodroid-samples/tree/master/Firebase/FCMNotifications

If not, could you give us more details of your issue, please?

Thanks

**Comment by gonzalonm** [comment]
@phoenix214 We have a potential fix for this issue. For use Firebase service, you must to init it before. To do this, try to add the following line in the last part of your `OnCreate` method:

https://gist.github.com/gonzalonm/7a9f96b36db70160c4aa52c35d3cfe2e#file-firebaseapp-cs-L25

This should fix the problem. If that is the case, please let us know and we can update this sample.

Thanks

**Comment by jacano** [comment]
Hitting the same issue. 
Does not fix the problem for me.

**Comment by gonzalonm** [comment]
Nice! @phoenix214 Please, could you test it on your end and notify us if everything is ok? Thanks
