### ISSUE TITLE
[SplashActivity] How to fit image?

### ISSUE THREAD

**Issue by Leobaillard** [xamarin/monodroid-samples#228]
Hi!

I implemented the SplashActivity example but my image overflows on the right and left hand sides of the screen. How can I make so the image automatically fits the screen width keeping its ratio?

Thanks!

**Comment by gonzalonm** [comment]
Related sample: https://github.com/xamarin/monodroid-samples/tree/master/SplashScreen

**Comment by gonzalonm** [comment]
Where are you adding that image? Can you paste here the code for that? Or refer any links?

Thanks

**Comment by Leobaillard** [comment]
I followed the example and created `splash_screen.xml` in the `Resources/drawable` directory of my Android projet.
```xml
<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
  <item>
    <color android:color="@color/window_background" />
  </item>
  <item>
    <bitmap
      android:src="@drawable/app_logo_white"
      android:tileMode="disabled"
      android:gravity="center"/>
  </item>
</layer-list>
```

`app_logo_white` is a png image that is present in the various `drawable` folders (hdpi, ldpi, mdpi, xhdpi, xxhdpi, xxxhdpi).

Here is what it looks like:
![image](https://user-images.githubusercontent.com/402250/31893829-da190a22-b80c-11e7-851d-c2f16f7fa24e.png)

The logo bleeds out on both sides: part of the S is missing on the left, and a full E on the right.

**Comment by gonzalonm** [comment]
Looks like the png has a big size compared with the resolutions and densities. One path to follow is play with its size using [this tool](https://romannurik.github.io/AndroidAssetStudio/) and keep in mind the [screen supports by Google](https://developer.android.com/guide/practices/screens_support.html).

The way you managed this is the correct one, but the image looks like much bigger than the required to each screens.

Also you can check the following post for more info: https://stackoverflow.com/a/11196513

**Comment by Edgaras91** [comment]
I am also having the same issue, the image "bleeds" the same way. Is there another way besides re-sizing the actual image?

**Comment by meJevin** [comment]
4 years later... no solution? 😄

**Comment by gigimatto88** [comment]
The same here, did you find a solution?

**Comment by rezamohamed** [comment]
ha, Nov 2021, still the same question. looks like the only way is to set a smaller image resolution in the drawable folder
