### ISSUE TITLE
Mono.Actionbarsherlock don't work on pre-Honeycomb Android devices

### ISSUE THREAD

**Issue by ghost** [xamarin/monodroid-samples#25]
Would you down minimum target to 2.2 or 2.1 (pre-Honeycomb)? I want to use this library for academic application. 

Thanks a lot.

**Comment by abhisheks360** [comment]
Thanks for Reported this issue.Yes You can down minimum target to 2.2 or 2.1 use library for academic  application. Here is the screencast:http://www.screencast.com/t/aoEUj3cZ

Hence I closing this issue.
Thanks!
