### ISSUE TITLE
Can not Export CREATOR Field for IParcelable instance

### ISSUE THREAD

**Issue by fullmetaltac** [xamarin/monodroid-samples#254]
#### Sample link

https://github.com/xamarin/monodroid-samples/blob/f944f42001fa134915069fa7bbb9cb493bfd446d/ExportAttribute/ExportAttributeTest/MainActivity.cs#L55
https://github.com/xamarin/monodroid-samples/blob/f944f42001fa134915069fa7bbb9cb493bfd446d/android5.0/Topeka/Topeka/Models/Player.cs#L18

#### Issue description

Can not ExportField  CREATOR for IParcelable instance

#### Steps to reproduce the issue

1.  Open Topeka sample.
2. Input login info.
3. Tap Login button.

#### What's the expected result?

- User successfully login.

#### What's the actual result?

- Application crashes.

#### Steps to reproduce the issue

1.  Open ExportAttributeTest sample.
2. Tap button.

#### What's the expected result?

- Parcelable object handled properly.

#### What's the actual result?

- Application crashes.

#### Additional details / screenshot (Optional)
![image](https://user-images.githubusercontent.com/5435980/34485695-9f9fda4c-efd4-11e7-9e8b-5f00514d1027.png)

InitializeCreator method is not reachable via debugger.

**Comment by pjcollins** [comment]
Closing as this is now being tracked against xamarin-android.
