### ISSUE TITLE
not showing paired devices.. always show not connected

### ISSUE THREAD

**Issue by belhekar** [xamarin/monodroid-samples#264]
#### Sample link

[paste here the link to sample]

#### Issue description

[provide an issue description]

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

#### Additional details / screenshot (Optional)

- 
-

**Comment by belhekar** [comment]
please help

**Comment by conceptdev** [comment]
unfortunately we cannot provide support here. please review our [support options page](https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/support-options)
