### ISSUE TITLE
Can the Xamarin.Forms be combined with Xamarin.IOS or Xamarin.Android in the same project? Is there an example?

### ISSUE THREAD

**Issue by ghd258** [xamarin/monodroid-samples#267]
Can the Xamarin.Forms be combined with Xamarin.IOS or Xamarin.Android in the same project? Is there an example?

**Comment by ghd258** [comment]
Can cross platform development Xamarin.Forms be combined with Xamarin.IOS or Xamarin.Android in the same project or mixed use?

**Comment by conceptdev** [comment]
Take a look at the documentation for "Native Forms":
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-forms
