### ISSUE TITLE
[Camera2Basic] Java.Lang.IllegalArgumentException: Surface had no valid native Surface.

### ISSUE THREAD

**Issue by stevegdavis** [xamarin/monodroid-samples#269]
#### Sample link

https://github.com/xamarin/monodroid-samples/tree/master/android5.0/Camera2Basic

#### Issue description
Java.Lang.IllegalArgumentException: Surface had no valid native Surface when taking picture

App crashes with Java.Lang.IllegalArgumentException when Picture button is pressed after switching to/back from another app.
#### Steps to reproduce the issue

1.  Build app with VS 2017 Community Edition
2. Press Picture and app saves pic.jpg as expected
3. Switch to another app
4. Switch back to the app and press Picture again, may have to repeat this several times to get the error

#### What's the expected result?
To save pic.jpg
-

#### What's the actual result?
Java.Lang.IllegalArgumentException exception is thrown in file Camera2BasicFragment.cs - CaptureStillPicture() method line that reads:- mCaptureSession.Capture(stillCaptureBuilder.Build(), new CameraCaptureStillPictureSessionCallback(this), null);
-

#### Additional details / screenshot (Optional)
Running on Samsung A5 Android 6 (example app doesn't even run on my Sony Xperia M4 running Android 5)
- 
![camera2basic illegal argument exception](https://user-images.githubusercontent.com/15140454/39628897-63584ea6-4fa2-11e8-8dea-8b7e4c109b32.JPG)

-

**Comment by NagoorBabu** [comment]
Hi, I am facing this issue in marshmallow. Can anyone please update on this regard.

**Comment by SDV-MINI-DEV-2** [comment]
Same problem here...

**Comment by evorios** [comment]
same problem, have no solution

**Comment by Raghav29Sharma** [comment]
Still facing ....any solution?
