### ISSUE TITLE
AAR bindings not showing any contents

### ISSUE THREAD

**Issue by ghost** [xamarin/monodroid-samples#270]
#### Sample link

Here is the tutorial: 
[https://developer.xamarin.com/guides/android/advanced_topics/binding-a-java-library/binding-an-aar/](https://developer.xamarin.com/guides/android/advanced_topics/binding-a-java-library/binding-an-aar/)
Actual code:
[https://github.com/xamarin/monodroid-samples/tree/master/JavaIntegration/AarBinding](https://github.com/xamarin/monodroid-samples/tree/master/JavaIntegration/AarBinding)

#### Issue description

AAR binding not showing any contents?

#### Steps to reproduce the issue

1.  Download tutorial
2.  Open Visual Studio 15.6.2
3.  Check object browser (click on Binding Test project -> references -> aarbinding)

#### What's the expected result?

- Should show at least some content?

![](https://developer.xamarin.com/guides/android/advanced_topics/binding-a-java-library/binding-an-aar/Images/11-object-browser-vs.png)

#### What's the actual result?

- ![capture1](https://user-images.githubusercontent.com/7578991/39819353-e73dbc8a-53ab-11e8-825a-a4f4d3aec80a.JPG)

#### Additional details / screenshot (Optional)

- 
-

**Comment by wodaidai** [comment]
same here, can't see anything in object explorer.
however, the sample project above does run correctly in VM (function works as expected). 
Maybe VS issue.
