### ISSUE TITLE
Camera2Basic multi capture callbacks with dual cameras with fix

### ISSUE THREAD

**Issue by smvernon** [xamarin/monodroid-samples#273]
Camera2Basic has an issue with dual cameras, it may only be on the lg g6 as it is the only dual camera phone I have to test on. When the picture button is pressed the capture request occurs twice. This may have been over looked because the sample is designed to only save one photo and override the currently saved one. The fix for this is simple and just one line of code added to the CameraCaptureListener class in the process method under the switch  State_Waiting_Lock add at line 37 owner.mState = Camera2BasicFragment.STATE_PICTURE_TAKEN; . 
<br />

'private void Process(CaptureResult result)
        {
            switch (owner.mState)
            {
                case Camera2BasicFragment.STATE_WAITING_LOCK:
                    {
                        Integer afState = (Integer)result.Get(CaptureResult.ControlAfState);
                        if (afState == null)
                        {
                            owner.mState = Camera2BasicFragment.STATE_PICTURE_TAKEN; //Include to avoid multiple capture callbacks occuring with dual cameras 
                            owner.CaptureStillPicture();                            
                        }'
<br/>
#### Steps to reproduce the issue
1.  To verify this issue a dual camera is needed.
2.  Change the code to allow more that one image to be saved at a time. Change Camera2BasicFragment.cs OnActivityCreated 

<br />
From:
<br />
public override void OnActivityCreated(Bundle savedInstanceState)
        {
            base.OnActivityCreated(savedInstanceState);
            mFile = new File(Activity.GetExternalFilesDir(null), "pic.jpg");
            mCaptureCallback = new CameraCaptureListener(this);
            mOnImageAvailableListener = new ImageAvailableListener(this, mFile);
}`
<br />
<br/>
To:
<br />
`public override void OnActivityCreated(Bundle savedInstanceState)
        {
            base.OnActivityCreated(savedInstanceState);
            mFile = new File(Activity.GetExternalFilesDir(null), "pic.jpg");
            mCaptureCallback = new CameraCaptureListener(this);
            mOnImageAvailableListener = new ImageAvailableListener(this, Activity.GetExternalFilesDir(null));
}`
<br/>
<br/>
in ImageAvailableListener.cs change the ImageSaver From:
<br />
`public ImageSaver(Image image, File file)
            {
                if (image == null)
                    throw new System.ArgumentNullException("image");
                if (file == null)
                    throw new System.ArgumentNullException("file");

                mImage = image;
                mFile = file;
}

To:
public ImageSaver(Image image, File file)
            {
                if (image == null)
                    throw new System.ArgumentNullException("image");
                if (file == null)
                    throw new System.ArgumentNullException("file");

                mImage = image;
                string filename = System.DateTime.Now.Minute.ToString() + System.DateTime.Now.Second.ToString() + System.DateTime.Now.Millisecond.ToString();
                mFile = new File( file, filename + ".jpg");
}

#### What's the expected result?

-A Single picture being taken.

#### What's the actual result?

-Two pictures being taken.

#

**Comment by jongleur1983** [comment]
Thanks for this issue. I'm not a maintainer here, but your hints saved my life today ;)
I'm going to prepare a Pull-Request with the changes you proposed as I think it should be part of the sample to work correctly.

**Comment by conceptdev** [comment]
I've never had a dual-camera Android phone either. @jongleur1983 a PR would be fantastic.

**Comment by jongleur1983** [comment]
see https://github.com/xamarin/monodroid-samples/pull/300

**Comment by conceptdev** [comment]
Thankyou both for your contribution.
