### ISSUE TITLE
FCMNotifications sample 

### ISSUE THREAD

**Issue by xdinos** [xamarin/monodroid-samples#285]
#### Issue description
When we are sending a notification message we are getting this error

10-30 18:07:18.732 I/art     (11332): Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.RemoteMessage>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/zza;
10-30 18:07:18.733 I/art     (11332):   at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
10-30 18:07:18.733 I/art     (11332):   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3144)
10-30 18:07:18.733 I/art     (11332):   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
10-30 18:07:18.733 I/art     (11332):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1550)
10-30 18:07:18.733 I/art     (11332):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
10-30 18:07:18.733 I/art     (11332):   at void android.os.Looper.loop() (Looper.java:154)
10-30 18:07:18.733 I/art     (11332):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
10-30 18:07:18.733 I/art     (11332):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
10-30 18:07:18.733 I/art     (11332):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:865)
10-30 18:07:18.733 I/art     (11332):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:755)
10-30 18:07:18.733 I/art     (11332): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/data/app/com.froggon.client-1/base.apk"],nativeLibraryDirectories=[/data/app/com.froggon.client-1/lib/x86, /data/app/com.froggon.client-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
10-30 18:07:18.733 I/art     (11332):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
10-30 18:07:18.733 I/art     (11332):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
10-30 18:07:18.733 I/art     (11332):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
10-30 18:07:18.733 I/art     (11332):   at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
10-30 18:07:18.733 I/art     (11332):   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3144)
10-30 18:07:18.733 I/art     (11332):   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
10-30 18:07:18.733 I/art     (11332):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1550)
10-30 18:07:18.733 I/art     (11332):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
10-30 18:07:18.733 I/art     (11332):   at void android.os.Looper.loop() (Looper.java:154)
10-30 18:07:18.733 I/art     (11332):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
10-30 18:07:18.733 I/art     (11332):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
10-30 18:07:18.733 I/art     (11332):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:865)
10-30 18:07:18.733 I/art     (11332):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:755)
10-30 18:07:18.733 I/art     (11332): 
10-30 18:07:18.733 I/art     (11332): Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.RemoteMessage>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/zza;
10-30 18:07:18.733 I/art     (11332):   at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
10-30 18:07:18.733 I/art     (11332):   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3144)
10-30 18:07:18.733 I/art     (11332):   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
10-30 18:07:18.733 I/art     (11332):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1550)
10-30 18:07:18.733 I/art     (11332):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
10-30 18:07:18.733 I/art     (11332):   at void android.os.Looper.loop() (Looper.java:154)
10-30 18:07:18.733 I/art     (11332):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
10-30 18:07:18.733 I/art     (11332):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
10-30 18:07:18.733 I/art     (11332):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:865)
10-30 18:07:18.734 I/art     (11332):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:755)
10-30 18:07:18.734 I/art     (11332): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/data/app/com.froggon.client-1/base.apk"],nativeLibraryDirectories=[/data/app/com.froggon.client-1/lib/x86, /data/app/com.froggon.client-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
10-30 18:07:18.734 I/art     (11332):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
10-30 18:07:18.734 I/art     (11332):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
10-30 18:07:18.734 I/art     (11332):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
10-30 18:07:18.734 I/art     (11332):   at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
10-30 18:07:18.734 I/art     (11332):   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3144)
10-30 18:07:18.734 I/art     (11332):   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
10-30 18:07:18.734 I/art     (11332):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1550)
10-30 18:07:18.734 I/art     (11332):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
10-30 18:07:18.734 I/art     (11332):   at void android.os.Looper.loop() (Looper.java:154)
10-30 18:07:18.734 I/art     (11332):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
10-30 18:07:18.734 I/art     (11332):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
10-30 18:07:18.734 I/art     (11332):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:865)
10-30 18:07:18.734 I/art     (11332):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:755)
10-30 18:07:18.734 I/art     (11332): 
10-30 18:07:18.734 I/art     (11332): Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.RemoteMessage>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/zza;
10-30 18:07:18.734 I/art     (11332):   at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
10-30 18:07:18.734 I/art     (11332):   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3144)
10-30 18:07:18.734 I/art     (11332):   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
10-30 18:07:18.734 I/art     (11332):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1550)
10-30 18:07:18.734 I/art     (11332):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
10-30 18:07:18.734 I/art     (11332):   at void android.os.Looper.loop() (Looper.java:154)
10-30 18:07:18.734 I/art     (11332):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
10-30 18:07:18.734 I/art     (11332):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
10-30 18:07:18.734 I/art     (11332):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:865)
10-30 18:07:18.734 I/art     (11332):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:755)
10-30 18:07:18.734 I/art     (11332): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/data/app/com.froggon.client-1/base.apk"],nativeLibraryDirectories=[/data/app/com.froggon.client-1/lib/x86, /data/app/com.froggon.client-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
10-30 18:07:18.734 I/art     (11332):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
10-30 18:07:18.734 I/art     (11332):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
10-30 18:07:18.735 I/art     (11332):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
10-30 18:07:18.735 I/art     (11332):   at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
10-30 18:07:18.735 I/art     (11332):   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3144)
10-30 18:07:18.735 I/art     (11332):   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
10-30 18:07:18.735 I/art     (11332):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1550)
10-30 18:07:18.735 I/art     (11332):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
10-30 18:07:18.735 I/art     (11332):   at void android.os.Looper.loop() (Looper.java:154)
10-30 18:07:18.735 I/art     (11332):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
10-30 18:07:18.735 I/art     (11332):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
10-30 18:07:18.735 I/art     (11332):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:865)
10-30 18:07:18.735 I/art     (11332):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:755)
10-30 18:07:18.735 I/art     (11332): 
10-30 18:07:18.735 D/Mono    (11332): Assembly Ref addref FCMNotifications[0xe9de51a0] -> Xamarin.Firebase.Messaging[0xe9de56e0]: 2
10-30 18:07:18.735 D/Mono    (11332): Assembly Ref addref Xamarin.Firebase.Messaging[0xe9de56e0] -> Xamarin.GooglePlayServices.Tasks[0xe9de5800]: 3
10-30 18:07:18.740 D/FirebaseMessaging(11332): Unknown intent action: com.google.firebase.MESSAGING_EVENT

**Comment by renaudLVLP** [comment]
@xdinos same issue ... Did you find a fix or the reason for that error ?
