### ISSUE TITLE
Update FCM Example: FirebaseInstanceId.Instance.Token is obsolete

### ISSUE THREAD

**Issue by BeanStalka** [xamarin/monodroid-samples#293]
In the FCM example we are to use the class MyFirebaseIIDService

this class has an override for OnTokenRefresh.

where we call FirebaseInstanceId.Instance.Token.

This call is deprecated.  In fact there is a whole new way to access the FCM Token

Including a new FirebaseMessagingService.OnNewToken() method that is supposed to be used to replace the OnTokenRefresh in the MyFirebaseIDService.

I have spent a couple of days digging on this one, and its very confusing with old samples and new samples mixing and matching.

There really is no definitive example on how to implement the new FCM that found.  Just a guide to convert to the new FCM which assumes I am using Android Studio.

So Frustrating.

According to this video from google: https://www.youtube.com/watch?v=IeexEiFprY8

And this migration guide: https://developers.google.com/cloud-messaging/android/android-migrate-fcm

Support for GMC could be gone as soon as April of this year,  As in 3 months!!!.

When attempting to use the InstanceIDListenerService  as a base class, I notices it was not available in the NuGet package.

Please update this package so that It has all of the new classes required to use Firebase Messaging the right way.  

Please remove all calls to deprecated methods, so we don't have to worry about our code breaking in production when Google decides to stop support for these deprecated methods.

Also, If I'm being 'paranoid' please explain to me how we are supposed to use this Nuget package to get the FCM token going forward.

Also please explain to me why the deprecated method is OK.

Thanks,

BeanStalka

**Comment by Dooks123** [comment]
Little over two and a half months after, no updates?

**Comment by dioscarr** [comment]
Is there any update on how to implement the new FCM libraries?
