### ISSUE TITLE
How to handle click event of more than one Button on Widget?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [xamarin/monodroid-samples#296]
I have follow this [SimpleWidget sample](https://github.com/xamarin/monodroid-samples/tree/master/SimpleWidget)
And now I need handle more than one button on Widget
I can not find any guide about this
I have ask on [Forums Xamarin](https://forums.xamarin.com/discussion/comment/372389#Comment_372389)
Thank you!

**Comment by AgentFire** [comment]
I've downloaded the same sample and it won't even work, the emulator says that the app has stopped. What a shame.
