### ISSUE TITLE
Unable to download the files

### ISSUE THREAD

**Issue by almedaspani** [xamarin/monodroid-samples#298]
I am attempting to download the files from this website
https://developer.xamarin.com/samples/monodroid/ApplicationFundamentals/Touch_start
 but i am unable to download it. It gives me the following error

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<link type="text/css" id="dark-mode" rel="stylesheet" href=""/>
<style type="text/css" id="dark-mode-custom-style"/>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:a27a33ed-901e-0054-3456-45be5e000000 Time:2019-07-28T15:12:48.6685234Z
</Message>
</Error>

Anyone aware of the issue?

Thanks

**Comment by conceptdev** [comment]
We are in the process of migrating our gallery to a new site - hopefully this link works:

https://docs.microsoft.com/en-us/samples/xamarin/monodroid-samples/applicationfundamentals-touch-start/
