### ISSUE TITLE
Where to add the App ID 

### ISSUE THREAD

**Issue by ivanh23** [xamarin/monodroid-samples#305]
Hello , i am new to Xamarin and in this example i dont see where can i add my App ID from AdMob , i know where to add the Banner ID .

**Comment by cheles** [comment]
Although this request is old, App ID should from AdMob goes into Main Activity:
`MobileAds.Initialize(ApplicationContext, "YOUR APP ID HERE FROM AdMob, has a ~ in it");
`
Check this [blog](https://montemagno.com/xamarinforms-google-admob-ads-in-android/) on how to do it.

**Comment by DonGlover** [comment]
My sample shows another way to approach it.
https://github.com/DonGlover/DonGlover-AdMobSample
