### ISSUE TITLE
error XA0009: Error while loading assembly: /Users/Projects/monodroid-samples/FragmentsWalkthrough/SupportLibFragments/obj/Release/android/assets/supportlibfragmentssample.dll

### ISSUE THREAD

**Issue by jpotts18** [xamarin/monodroid-samples#31]
I have been trying to build the Support Lib Fragments inside the FragmentWalkthrough on a Mac. I have done the following. 
1. Added a new android-support-v4.jar file to the SupportLib folder.
2. Set the build action of the new JAR as Android Java Library.
3. Added the launcher images that were missing. 
4. I got this error.

Warnings:

/Users/developer/Projects/monodroid-samples/FragmentsWalkthrough/SupportLibFragments/SupportLibFragments.csproj (Build) ->
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets (_ResolveSatellitePaths target) ->

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets:  warning : Reference 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' not resolved
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets:  warning : Reference 'Mono.Android.Support.v4, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' not resolved
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets:  warning : Reference 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' not resolved
```

Errors:

/Users/developer/Projects/monodroid-samples/FragmentsWalkthrough/SupportLibFragments/SupportLibFragments.csproj (Build) ->
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets (_GenerateJavaStubs target) ->

```
: error XA0009: Error while loading assembly: /Users/developer/Projects/monodroid-samples/FragmentsWalkthrough/SupportLibFragments/obj/Release/android/assets/supportlibfragmentssample.dll

 3 Warning(s)
 1 Error(s)
```

I tried the same thing on windows and I was able to build to a phone. I have also had some problem with my phones ABI, so I went into the Project Settings and I added the (armeabi-v7a). 

Deploying in Debug mode works on mac with the same configuration.
Differences between release and debug build 

Linker was set to 
- link sdk's only in release mode
- dont link in Debug mode. 

General
- Enable optimzations was selected for release mode

**Comment by DrTJ** [comment]
Thank you @jpotts18 
Your solution worked for me!
