### ISSUE TITLE
Exception "Bad notification" running sample

### ISSUE THREAD

**Issue by LeonSweden** [xamarin/monodroid-samples#313]
After adding to manifest required but missing permission: 
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>

I get this error when pressing **START SERVICE**:

Android.Util.AndroidRuntimeException: 'Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 actions=2 vis=PRIVATE)'

I suggest that you do rewrite this sample to current Android version.

**Comment by Deba22** [comment]
@LeonSweden did you find a solution to this? even im facing the same issue. Please help!

**Comment by amr-moomen** [comment]
I'm facing the same issue. any help!

**Comment by Deba22** [comment]
I was able to get it working by using the below code while registering for a foreground service:

 String NOTIFICATION_CHANNEL_ID = "com.test.testapp";
                String channelName = "test app service";
                NotificationChannel chan = new NotificationChannel(NOTIFICATION_CHANNEL_ID, channelName, NotificationManager.ImportanceNone);
                chan.LockscreenVisibility = NotificationVisibility.Private;
                NotificationManager manager = (NotificationManager)GetSystemService(Context.NotificationService);
                manager.CreateNotificationChannel(chan);

                NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this, NOTIFICATION_CHANNEL_ID);
                Notification notification = notificationBuilder.SetOngoing(true)
                        .SetSmallIcon(Resource.Drawable.ic_stat_name)
                        .SetContentTitle("App is running in background")
                        .SetPriority(1)
                        .SetCategory(Notification.CategoryService)
                        .Build();
               
                StartForeground(Constants.SERVICE_RUNNING_NOTIFICATION_ID, notification);

 I hope this helps you.

**Comment by tatapuchi** [comment]
NotificationManager.Importance none is obsolete and will be removed, use NotificationImportance.None instead

**Comment by johnjore** [comment]
Combining the two posts above, this is my replacement (its half baked, and half implemented in my app, hence the namespace changes etc), but my app does not crash at startup anymore.

```
void RegisterForegroundService()
		{
/*			
			var notification = new Notification.Builder(this)
				.SetContentTitle(Resources.GetString(Resource.String.app_name))
				.SetContentText(Resources.GetString(Resource.String.notification_text))
				.SetSmallIcon(Resource.Drawable.route)
				.SetContentIntent(BuildIntentToShowMainActivity())
				.SetOngoing(true)
				.AddAction(BuildRestartTimerAction())
				.AddAction(BuildStopServiceAction())
				.Build();
*/

			String NOTIFICATION_CHANNEL_ID = "no.jore.hajk";
			String channelName = "test app service";
			NotificationChannel chan = new NotificationChannel(NOTIFICATION_CHANNEL_ID, channelName, NotificationImportance.None);
			chan.LockscreenVisibility = NotificationVisibility.Private;
			NotificationManager manager = (NotificationManager)GetSystemService(Context.NotificationService);
			manager.CreateNotificationChannel(chan);

			NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this, NOTIFICATION_CHANNEL_ID);
			Notification notification = notificationBuilder.SetOngoing(true)
					.SetSmallIcon(Resource.Drawable.route)
					.SetContentTitle("App is running in background")
					.SetPriority(1)
					.SetCategory(Notification.CategoryService)
					.Build();

			// Enlist this instance of the service as a foreground service
			StartForeground(PrefsActivity.SERVICE_RUNNING_NOTIFICATION_ID, notification);
		}
```

Updating the sample to a working version would be nice
