### ISSUE TITLE
GetExternalStorageDirectory is deprecated.

### ISSUE THREAD

**Issue by roshanbhore27** [xamarin/monodroid-samples#317]
#### Sample link

https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory()
monodroid-samples/LocalFiles/LocalFiles/

#### Issue description

GetExternalStorageDirectory is deprecated.

#### Steps to reproduce the issue

1.  monodroid-samples/LocalFiles/LocalFiles/

#### What's the expected result?
Saving a document to Public Document Folder.
#### What's the actual result?

Document is getting saved to App Document Folder. ( App/data/com.company.name/files/documents/)

**Comment by yshteinm** [comment]
Any updates on this?
