### ISSUE TITLE
Facebook example error

### ISSUE THREAD

**Issue by masterdimar** [xamarin/monodroid-samples#32]
If I have installed the facebook application, the authentication with Facebook hangs with the error "login fail please contact the marker of this app and ask them to issue 1732910 to facebook".

If I uninstall the facebook application, the authentications works fine.

**Comment by Abhishekk360** [comment]
Thanks you for reporting this issue. I have checked this issue with latest sample. This issue is  working fine.I am successfully able to login the facebook application. Here is the screencast for the same: http://www.screencast.com/t/jPJnIGAqg.

Hence closing this issue.

Thanks!
