### ISSUE TITLE
error when building monodroid-samples/android5.0/Camera2VideoSample: Unknown flag -p 

### ISSUE THREAD

**Issue by DavidShukvani** [xamarin/monodroid-samples#320]
#### Sample link

[Url to sample](https://github.com/xamarin/monodroid-samples/tree/master/android5.0/Camera2VideoSample)

#### Issue description

I have downloaded the zip file from [Code samples](https://docs.microsoft.com/en-gb/samples/xamarin/monodroid-samples/android50-camera2videosample/) and when trying to build and deploy the solution to Emulator or real phone it gives this error: 
```
ANDZA0000: ERROR: unknown flag -p
unknown flag -p
ANDZA0000: ERROR: unknown flag -p
ANDZA0000: Zip alignment utility
Zip alignment utility
ANDZA0000: Copyright (C) 2009 The Android Open Source Project
Copyright (C) 2009 The Android Open Source Project
ANDZA0000: 
ANDZA0000: Usage: zipalign [-f] [-v] <align> infile.zip outfile.zip
Usage: zipalign [-f] [-v] <align> infile.zip outfile.zip
ANDZA0000:        zipalign -c [-v] <align> infile.zip
       zipalign -c [-v] <align> infile.zip
ANDZA0000: 
ANDZA0000:   <align>: alignment in bytes, e.g. '4' provides 32-bit alignment
  <align>: alignment in bytes, e.g. '4' provides 32-bit alignment
ANDZA0000:   -c: check alignment only (does not modify file)
  -c: check alignment only (does not modify file)
ANDZA0000:   -f: overwrite existing outfile.zip
  -f: overwrite existing outfile.zip
ANDZA0000:   -v: verbose output
  -v: verbose output
Done building project "Camera2VideoSample.csproj" -- FAILED.
```
#### Steps to reproduce the issue

1.  Download the zip file from [code samples page](https://docs.microsoft.com/en-gb/samples/xamarin/monodroid-samples/android50-camera2videosample/)
2. Unzip
3. Deploy to Android 7.1 version 

#### What's the expected result?

App to be installed and launched

#### What's the actual result?

Errors in output window

**Comment by Alluseri** [comment]
hi almost 3 years later, issue is still here
