### ISSUE TITLE
Android 12 Splash Screen API update

### ISSUE THREAD

**Issue by ivandamyanov** [xamarin/monodroid-samples#328]
#### Sample link
New [Splash Screen API](https://developer.android.com/guide/topics/ui/splash-screen) 

#### Issue description

With Android 12 comes a new [Splash Screen API](https://developer.android.com/guide/topics/ui/splash-screen) which offers a migration guide and suggests against having a separate Activity for your splash screen. 

Any plans to update the documentation on how to use that with Xamarin.Android ?

**Comment by alirong** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已经收到您的邮件。谢谢

**Comment by BrianOney** [comment]
Facing the same issue. Any plans for updating the docs? Anyone have a Xamarin Android 12 splash screen implementation they can share?
