### ISSUE TITLE
BluetoothLeGatt

### ISSUE THREAD

**Issue by avantol** [xamarin/monodroid-samples#39]
In BluetoothLeGatt/DeviceControlActivity.cs, should use "&" instead of "|" when operating on a GattProperty to determine if property is "GattProperty.Read", etc.

**Comment by Abhishekk360** [comment]
Thanks for reporting this issue. I have checked this issue with latest updated sample. Now this issue is implemented there. Here is the screencast: http://www.screencast.com/t/WeBoFldrgjj

Hence closing this issue.

Thanks!
