### ISSUE TITLE
VoiceRecognition demo throws java.lang.NullPointerException

### ISSUE THREAD

**Issue by genereddick** [xamarin/monodroid-samples#41]
Running the VoiceRecognition sample in ApiDemo throws the following error both in an emulator and on a phone.

[monodroid-gc] GREF GC Threshold: 46800
[MonoDroid] Xamarin/Android Trial Mode Active
[Adreno200-EGLSUB] <ConfigWindowMatch:2087>: Format RGBA_8888.
[] <s3dReadConfigFile:75>: Can't open file for reading
[] <s3dReadConfigFile:75>: Can't open file for reading
[AbsListView] Get MotionRecognitionManager
[Adreno200-EGLSUB] <ConfigWindowMatch:2087>: Format RGBA_8888.
[AbsListView] Get MotionRecognitionManager
[Adreno200-EGLSUB] <ConfigWindowMatch:2087>: Format RGBA_8888.
[ResourceType] getEntry failing because entryIndex 129 is beyond type entryCount 4
[AbsListView] Get MotionRecognitionManager
[VoiceRecognition] Sending broadcast
[MonoDroid] UNHANDLED EXCEPTION: Java.Lang.NullPointerException: Exception of type 'Java.Lang.NullPointerException' was thrown.
[MonoDroid] at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (intptr,intptr,intptr,Android.Runtime.JValue[]) <0x00088>
[MonoDroid] at Android.Content.ContextWrapper.SendOrderedBroadcast (Android.Content.Intent,string,Android.Content.BroadcastReceiver,Android.OS.Handler,Android.App.Result,string,Android.OS.Bundle) <0x006ab>
[MonoDroid] at MonoDroid.ApiDemo.VoiceRecognition.RefreshVoiceSettings () <0x00087>
[MonoDroid] at MonoDroid.ApiDemo.VoiceRecognition.OnCreate (Android.OS.Bundle) <0x0022b>
[MonoDroid] at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (intptr,intptr,intptr) <0x00057>
[MonoDroid] at (wrapper dynamic-method) object.4ef9ec1f-9181-40b1-8740-b5edc67b0142 (intptr,intptr,intptr) <0x00043>
[MonoDroid] 
[MonoDroid]   --- End of managed exception stack trace ---
[MonoDroid] java.lang.NullPointerException
[MonoDroid] 	at android.app.ContextImpl.sendOrderedBroadcast(ContextImpl.java:1125)
[MonoDroid] 	at android.content.ContextWrapper.sendOrderedBroadcast(ContextWrapper.java:344)
[MonoDroid] 	at monodroid.apidemo.VoiceRecognition.n_onCreate(Native Method)
[MonoDroid] 	at monodroid.apidemo.VoiceRecognition.onCreate(VoiceRecognition.java:29)
[MonoDroid] 	at android.app.Activity.performCreate(Activity.java:5179)
[MonoDroid] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
[MonoDroid] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
[MonoDroid] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
[MonoDroid] 	at android.app.ActivityThread.access$700(ActivityThread.java:143)
[MonoDroid] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:137)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:4950)
[MonoDroid] 	at java.lang.reflect.Method.invokeNative(Native Method)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Method.java:511)
[MonoDroid] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
[MonoDroid] 	at dalvik.system.NativeStart.main(Native Method)
[mono] 
[mono] Unhandled Exception:
[mono] Java.Lang.NullPointerException: Exception of type 'Java.Lang.NullPointerException' was thrown.
[mono] at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (intptr,intptr,intptr,Android.Runtime.JValue[]) <0x00088>
[mono] at Android.Content.ContextWrapper.SendOrderedBroadcast (Android.Content.Intent,string,Android.Content.BroadcastReceiver,Android.OS.Handler,Android.App.Result,string,Android.OS.Bundle) <0x006ab>
[mono] at MonoDroid.ApiDemo.VoiceRecognition.RefreshVoiceSettings () <0x00087>
[mono] at MonoDroid.ApiDemo.VoiceRecognition.OnCreate (Android.OS.Bundle) <0x0022b>
[mono] at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (intptr,intptr,intptr) <0x00057>
[mono] at (wrapper dynamic-method) object.4ef9ec1f-9181-40b1-8740-b5edc67b0142 (intptr,intptr,intptr) <0x00043>
[mono] 
[mono]   --- End of managed exception stack trace ---
[mono] java.lang.NullPointerException
[mono] 	at android.app.ContextImpl.sendOrderedBroadcast(ContextImpl.java:1125)
[mono] 	at android.content.ContextWrapper.sendOrderedBroadcast(ContextWrapper.java:344)
[mono] 	at monodroid.apidemo.VoiceRe
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.NullPointerException: Exception of type 'Java.Lang.NullPointerException' was thrown.
[mono-rt] at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (intptr,intptr,intptr,Android.Runtime.JValue[]) <0x00088>
[mono-rt] at Android.Content.ContextWrapper.SendOrderedBroadcast (Android.Content.Intent,string,Android.Content.BroadcastReceiver,Android.OS.Handler,Android.App.Result,string,Android.OS.Bundle) <0x006ab>
[mono-rt] at MonoDroid.ApiDemo.VoiceRecognition.RefreshVoiceSettings () <0x00087>
[mono-rt] at MonoDroid.ApiDemo.VoiceRecognition.OnCreate (Android.OS.Bundle) <0x0022b>
[mono-rt] at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (intptr,intptr,intptr) <0x00057>
[mono-rt] at (wrapper dynamic-method) object.4ef9ec1f-9181-40b1-8740-b5edc67b0142 (intptr,intptr,intptr) <0x00043>
[mono-rt] 
[mono-rt]   --- End of managed exception stack trace ---
[mono-rt] java.lang.NullPointerException
[mono-rt] 	at android.app.ContextImpl.sendOrderedBroadcast(ContextImpl.java:1125)
[mono-rt] 	at android.content.ContextWrapper.sendOrderedBroadcast(ContextWrapper.java:344)
[mono-rt] 	at monodroid.ap

**Comment by abhisheks360** [comment]
Thanks for reporting the issue. I am unable  reproduce this issue at my end. I have checked this issue with latest updated sample.Now it working fine.
Hence i closing this issue.
Thanks!
