### ISSUE TITLE
ViewPagerIndicator doesn't compile :(

### ISSUE THREAD

**Issue by ghost** [xamarin/monodroid-samples#46]
I try to compile this project using Xamarin.Android 4.8.3 but it doesn't work :/ :/

**Comment by abhisheks360** [comment]
Thanks for reporting the issue. I am no longer to reproduce this issue at my end. I have checked this issue with latest updated sample. Now ViewPagerIndicator sample is compile sucessfully . Here is the screencast for the same:http://www.screencast.com/t/ghG4FrNH

Hence I closing this issue.
Thanks!
