### ISSUE TITLE
Android L project only seems to work if Lollipop is already installed

### ISSUE THREAD

**Issue by wgrand** [xamarin/monodroid-samples#63]
**[HelloToolbar] (https://github.com/xamarin/monodroid-samples/tree/master/android_l/Toolbar/HelloToolbar)**

Only seems to work if Lollipop is already on the device.  So, why use AppCompat?

I just get the following build errors:

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Tool exited with code: 1. Output: obj/Debug/res/values/styles.xml:1: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Theme.Material.Light.DarkActionBar'.

    obj/Debug/res/values/styles.xml:2: error: Error: No resource found that matches the given name: attr 'android:colorAccent'.
    obj/Debug/res/values/styles.xml:1: error: Error: No resource found that matches the given name: attr 'android:colorPrimary'.
    obj/Debug/res/values/styles.xml:1: error: Error: No resource found that matches the given name: attr 'android:colorPrimaryDark'.

**Comment by jamesmontemagno** [comment]
The HelloToolbar example is for using Lollipop only, it does not use AppCompat at all. 

You can find a AppCompat version of it though here: https://github.com/xamarin/monodroid-samples/tree/master/Supportv7/AppCompat/Toolbar
