### ISSUE TITLE
Wear.GridViewPager doesn't compile with latest Xamarin.Android.Wear Package

### ISSUE THREAD

**Issue by SolidNerd** [xamarin/monodroid-samples#75]
Hey, i tried to the [GridViewPager Sample](https://github.com/xamarin/monodroid-samples/tree/master/wear/GridViewPager) and it doesn't build. It builds with Xamarin.Android.Wear Bindings 1.0.0-preview7. The problem comes with latest Xamarin.Android.Wear Bindings, because in 1.1.0.2 the ImageReference Class got removed from the dll. Is there any Solution to use it with latest Xamarin.Android.Wear Bindings ?

**Comment by jamesmontemagno** [comment]
All fixed up
