### ISSUE TITLE
GCM Notifications

### ISSUE THREAD

**Issue by CabbyM** [xamarin/monodroid-samples#96]
Hi, 

I've tried your sample on Xamarin, and slow followed instructions how to configure gcm service on google. I got my server APIKEY and also the Regid from my device. Im using your server to send a push notification but im having problem receiving these notifications. The statuscode from the server after sending e push notification is on OK but stil not receiving pushnotifications. I spend a whole day trying to get this to work but stil no results. Can u please help me?

**Comment by HenrikThien** [comment]
Did you add the permissions and intent filters?

**Comment by CabbyM** [comment]
Hi Hernik,

I've used the client sample from the project remotenotifications. The only thing i've changed in the androidmanifest is the package name so it can access the gcm to receive the reg_id. I'm getting a reg_id, after that i try sending a notification but not receiving it. My server sends this as json
{
  "to": "/topics/global",
  "data": {
    "message": "Hello",
    "registration_ids": [
      "EnwB-7GBkrAVElQRDx-rSpS00qdQoAI"
    ]
  }
}

**Comment by HenrikThien** [comment]
You need to add use-permissions in Manifest.xml file and Intent filters in the IntentService class.
<addr>
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.WAKE_LOCK" />
  <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
  <uses-permission android:name="PACKAGE_NAME.permission.C2D_MESSAGE" />
  <permission android:name="PACKAGE_NAME.permission.C2D_MESSAGE" android:protectionLevel="signature" />
</addr>

**Comment by CabbyM** [comment]
I'm using the sample of the ClientApp and it has these permissions in the manifest and also in te intentservice class. Am i missing something?

[Service (Exported = false), IntentFilter (new [] { "com.google.android.c2dm.intent.RECEIVE" })]
[Service(Exported = false), IntentFilter(new[] { "com.google.android.gms.iid.InstanceID" })]
[Service (Exported = false)] in the RegistrationIntentService

In the AndroidManifest.xml i'm using 
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	<uses-permission android:name="android.permission.INTERNET" />
	<permission android:name="com.cabby.drone.permission.C2D_MESSAGE" android:protectionLevel="signature" />
	<uses-permission android:name="com.cabby.drone.permission.C2D_MESSAGE" />
<receiver android:name="com.google.android.gms.gcm.GcmReceiver" 
       android:exported="true" 
       android:permission="com.google.android.c2dm.permission.SEND">
        <intent-filter>
	<action android:name="com.google.android.c2dm.intent.RECEIVE" />
	<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
	<category android:name="com.cabby.drone" />
	</intent-filter>
</receiver>

**Comment by HenrikThien** [comment]
are you sure, that you got the play store on your test device?

**Comment by CabbyM** [comment]
I've resolved this issue yesterday when i noticed that i was using the google api key instead of the project number. Thats why i wasn't receiving any notifications.

**Comment by pjcollins** [comment]
Closing due to last comment.
