### ISSUE TITLE
CardView samples no longer build

### ISSUE THREAD

**Issue by pgulotta** [xamarin/monodroid-samples#98]
Since your last release of Xamarin, samples using the CardView library no longer build :(.     I have the latest Xamarin and Android SDK software stack.   What's up?

**Comment by Abhishekk360** [comment]
Thanks for reporting this issue. I have checked this issue with latest updated sample. I am successfully able to build the application at my end. Here is the screencast for the same: http://www.screencast.com/t/mnxEqiBy5y

Hence closing this issue.

Thanks!
